name:                servant-benchmark
version:             0.1.0.0
github:              "3kyro/servant-benchmark"
license:             BSD3
author:              "Kyriakos Papachrysanthou"
maintainer:          "papachrysanthou.k@gmaim.com"
copyright:           "2021 Kyriakos Papachrysanthou"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/3kyro/servant-benchmark#README>

dependencies:
- base >= 4.7 && < 5
- text
- servant
- servant-server
- http-types
- case-insensitive
- utf8-string
- QuickCheck
- aeson
- warp
- base64-bytestring
- bytestring
- yaml
- http-media

library:
  source-dirs: src
  ghc-options:
  - -Wall


tests:
  servant-benchmark-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fprint-potential-instances
    dependencies:
    - servant-benchmark
    - hspec
